"""Added password reset token fields

Revision ID: 0567c5d38346
Revises: f6b0caee657b
Create Date: 2026-08-17 15:27:53.501274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0567c5d38346'
down_revision = 'f6b0caee657b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('Relationships', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'user', ['followed_id'], ['user_id'], ondelete='CASCADE')
    #     batch_op.create_foreign_key(None, 'user', ['follower_id'], ['user_id'], ondelete='CASCADE')

    # with op.batch_alter_table('recipes', schema=None) as batch_op:
    #     batch_op.alter_column('instructions',
    #            existing_type=sa.TEXT(),
    #            type_=sa.JSON(),
    #            existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')

    # with op.batch_alter_table('recipes', schema=None) as batch_op:
    #     batch_op.alter_column('instructions',
    #            existing_type=sa.JSON(),
    #            type_=sa.TEXT(),
    #            existing_nullable=False)

    # with op.batch_alter_table('Relationships', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'user', ['follower_id'], ['user_id'])
    #     batch_op.create_foreign_key(None, 'user', ['followed_id'], ['user_id'])

    # ### end Alembic commands ###
