"""added recipe class

Revision ID: 13da4bd10dad
Revises: 81bf4d98e35b
Create Date: 2026-08-06 23:26:12.963296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13da4bd10dad'
down_revision = '81bf4d98e35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_platform', sa.String(length=100), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('author', sa.VARCHAR(length=80), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipe')
    # ### end Alembic commands ###
