"""added helper function, and explicit table name

Revision ID: 22fc34502f44
Revises: bab82016e87f
Create Date: 2026-08-07 14:29:31.019662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '22fc34502f44'
down_revision = 'bab82016e87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_platform', sa.String(length=100), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.drop_table('recipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('source_platform', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ingredients', sqlite.JSON(), nullable=False),
    sa.Column('instructions', sa.TEXT(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('submitted_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.drop_table('recipes')
    # ### end Alembic commands ###
