"""added indexing to recipeIngredients

Revision ID: 3941765b84aa
Revises: 492c27abd6c4
Create Date: 2026-09-22 16:51:01.041979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3941765b84aa'
down_revision = '492c27abd6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RecipeIngredient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_RecipeIngredient_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_RecipeIngredient_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RecipeIngredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_RecipeIngredient_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_RecipeIngredient_ingredient_id'))

    # ### end Alembic commands ###
