"""Removing cook_time and prep_time from Recipe because apparently cook_time is not implemented in the recipe-scraper package

Revision ID: 41b4b996f6ca
Revises: 45e100c6262e
Create Date: 2026-09-20 14:52:53.283214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b4b996f6ca'
down_revision = '45e100c6262e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('prep_time')
        batch_op.drop_column('cook_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cook_time', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True))
        batch_op.add_column(sa.Column('prep_time', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True))

    # ### end Alembic commands ###
