"""updating tags to be a json object

Revision ID: 45e100c6262e
Revises: bfe720044963
Create Date: 2026-09-20 11:18:33.944873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '45e100c6262e'
down_revision = 'bfe720044963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('nutrients',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0.0'"))
        batch_op.alter_column('servings',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('servings',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0.0'"))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('nutrients',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))

    # ### end Alembic commands ###
