"""updated UserPantry model

Revision ID: 492c27abd6c4
Revises: aedf1495c322
Create Date: 2026-09-21 20:26:14.153378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492c27abd6c4'
down_revision = 'aedf1495c322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserPantry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserPantry_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_UserPantry_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_ingredient', ['user_id', 'ingredient_id'])
        batch_op.drop_constraint(batch_op.f('fk_UserPantry_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_UserPantry_ingredient_id_ingredient'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_UserPantry_user_id_user'), 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_UserPantry_ingredient_id_ingredient'), 'ingredient', ['ingredient_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserPantry', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_UserPantry_ingredient_id_ingredient'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_UserPantry_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_UserPantry_ingredient_id_ingredient'), 'ingredient', ['ingredient_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_UserPantry_user_id_user'), 'user', ['user_id'], ['user_id'])
        batch_op.drop_constraint('uq_user_ingredient', type_='unique')
        batch_op.drop_index(batch_op.f('ix_UserPantry_user_id'))
        batch_op.drop_index(batch_op.f('ix_UserPantry_ingredient_id'))

    # ### end Alembic commands ###
