"""updated Recipe rel. to include tags, last_updated, and updated status of existing attrs to be  non-nullable

Revision ID: 7ce10a98b44a
Revises: 22fc34502f44
Create Date: 2026-08-09 15:08:39.664602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce10a98b44a'
down_revision = '22fc34502f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.alter_column('source_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('source_platform',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('source_platform',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('source_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.drop_column('last_updated')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
