"""empty message

Revision ID: 9430331946d1
Revises: 
Create Date: 2026-08-22 15:30:22.025493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9430331946d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('Relationships',
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.user_id'], name=op.f('fk_Relationships_followed_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.user_id'], name=op.f('fk_Relationships_follower_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('followed_id', 'follower_id', name=op.f('pk_Relationships'))
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], name=op.f('fk_ingredient_created_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient'))
    )
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_platform', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('tags', sa.String(length=100), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.user_id'], name=op.f('fk_recipes_submitted_by_user')),
    sa.PrimaryKeyConstraint('recipe_id', name=op.f('pk_recipes'))
    )
    op.create_table('RecipeIngredient',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_RecipeIngredient_ingredient_id_ingredient'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], name=op.f('fk_RecipeIngredient_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id', name=op.f('pk_RecipeIngredient'))
    )
    op.create_table('SavedRecipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], name=op.f('fk_SavedRecipes_recipe_id_recipes')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_SavedRecipes_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_SavedRecipes'))
    )
    op.create_table('UserPantry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_UserPantry_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_UserPantry_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserPantry'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserPantry')
    op.drop_table('SavedRecipes')
    op.drop_table('RecipeIngredient')
    op.drop_table('recipes')
    op.drop_table('ingredient')
    op.drop_table('Relationships')
    op.drop_table('user')
    # ### end Alembic commands ###
