"""Added unique constraints and made RecipeIngredients have a whole new id as pk instead of (ingredient_id, recipe_ip) pk

Revision ID: 9436a138ee9f
Revises: a5ed0295fd50
Create Date: 2026-09-18 22:46:31.639154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9436a138ee9f'
down_revision = 'a5ed0295fd50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RecipeIngredient', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('recipe_ingredient_id', sa.Integer(), autoincrement=True, nullable=False, server_default='1')
        )

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ingredient_name'), ['name'])

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_recipes_source_url', ['source_url'])
        batch_op.create_unique_constraint('uq_user_recipe_title', ['submitted_by', 'title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_recipe_title', type_='unique')
        batch_op.drop_constraint('uq_recipes_source_url', type_='unique')

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ingredient_name'), type_='unique')

    with op.batch_alter_table('RecipeIngredient', schema=None) as batch_op:
        batch_op.drop_column('recipe_ingredient_id')

    # ### end Alembic commands ###
