"""updated SavedRecipes

Revision ID: aedf1495c322
Revises: 41b4b996f6ca
Create Date: 2026-09-20 23:30:03.053160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedf1495c322'
down_revision = '41b4b996f6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SavedRecipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_SavedRecipes_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_SavedRecipes_recipe_id_recipes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_SavedRecipes_user_id_user'), 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_SavedRecipes_recipe_id_recipes'), 'recipes', ['recipe_id'], ['recipe_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SavedRecipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_SavedRecipes_recipe_id_recipes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_SavedRecipes_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_SavedRecipes_recipe_id_recipes'), 'recipes', ['recipe_id'], ['recipe_id'])
        batch_op.create_foreign_key(batch_op.f('fk_SavedRecipes_user_id_user'), 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
