"""updated Recipe class, added created_by column

Revision ID: bab82016e87f
Revises: 13da4bd10dad
Create Date: 2026-08-07 12:59:13.829571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab82016e87f'
down_revision = '13da4bd10dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
