"""adding new attrs to Recipe model

Revision ID: bfe720044963
Revises: 9436a138ee9f
Create Date: 2026-09-20 11:00:20.378190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe720044963'
down_revision = '9436a138ee9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutrients', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('cook_time', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('prep_time', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('total_time', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('servings', sa.String(length=100), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('servings')
        batch_op.drop_column('rating')
        batch_op.drop_column('category')
        batch_op.drop_column('total_time')
        batch_op.drop_column('prep_time')
        batch_op.drop_column('cook_time')
        batch_op.drop_column('description')
        batch_op.drop_column('nutrients')

    # ### end Alembic commands ###
