"""followers2

Revision ID: f6b0caee657b
Revises: cfdc6fd5a1ef
Create Date: 2026-08-11 10:03:43.419683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b0caee657b'
down_revision = 'cfdc6fd5a1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Relationships',
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('followed_id', 'follower_id')
    )
    op.drop_table('UserRelationships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserRelationships',
    sa.Column('followed_id', sa.INTEGER(), nullable=False),
    sa.Column('follower_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('followed_id', 'follower_id')
    )
    op.drop_table('Relationships')
    # ### end Alembic commands ###
